export enum ErrorCode {
    // AUTH
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
    AUTH_EMAIL_NOT_VERIFIED = "AUTH_EMAIL_NOT_VERIFIED",
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
    AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",

    // USER
    USER_NOT_FOUND = "USER_NOT_FOUND",
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",

    NOT_FOUND = "NOT_FOUND",

    // SESSION
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
    SESSION_UNAUTHORIZED = "SESSION_UNAUTHORIZED",
    SESSION_EXPIRED = "SESSION_EXPIRED",

    // VALIDATION
    VALIDATION_ERROR = "VALIDATION_ERROR",

    // SYSTEM
    INTERNAL_ERROR = "INTERNAL_ERROR",
}